'use client';
import { useState } from 'react';

const nav = {
  'Trail operations': ['Control center','Operations display','People & groups','Trail devices','Communications','Locations','Safety & alerts'],
  'Local server': ['Server foundation','Offline readiness','Updates','Backups','Server settings'],
};
const people = [
  {name:'Alex',place:'North trailhead',state:'Connected'},
  {name:'Jordan',place:'Pine overlook',state:'Moving'},
  {name:'Casey',place:'Creek crossing',state:'Stopped'},
  {name:'Morgan',place:'Base camp',state:'Connected'}
];
export default function Home(){
  const [active,setActive]=useState('Control center');
  const [locations,setLocations]=useState(true);
  const [alerts,setAlerts]=useState(true);
  const [compact,setCompact]=useState(false);
  const [selectedPerson,setSelectedPerson]=useState('Alex');
  if(active==='Operations display')return <OperationsDisplay onExit={()=>setActive('Control center')}/>;
  return <main className={'app '+(compact?'compact':'')}>
    <aside className="sidebar">
      <div className="brand"><b>LU</b><span><strong>LIMITED UNDERGROUND</strong><small>TRAIL SERVER</small></span></div>
      <div className="local"><i/> Local server</div>
      <nav>{Object.entries(nav).map(([group,items])=><section key={group}><p>{group}</p>{items.map(item=><button key={item} className={active===item?'active':''} onClick={()=>setActive(item)}><span>{icon(item)}</span>{item}</button>)}</section>)}</nav>
      <footer><strong>Architecture option V0</strong><span>Demonstration data only</span></footer>
    </aside>
    <div className="workspace">
      <header><div><p>LIMITED UNDERGROUND / TRAIL</p><h1>{active}</h1></div><div className="header-status"><span className="demo">DEMONSTRATION · NOT OPERATIONAL</span><span className="online"><i/> Simulated status</span></div></header>
      <div className="content"><Content active={active} setActive={setActive} selectedPerson={selectedPerson} setSelectedPerson={setSelectedPerson} locations={locations} setLocations={setLocations} alerts={alerts} setAlerts={setAlerts} compact={compact} setCompact={setCompact}/></div>
      <div className="ops-footer"><span><b>PINE RIDGE PARK</b> · PERMANENT SITE</span><strong>MODE: OFF-ROAD</strong></div>
    </div>
  </main>;
}

type Props={active:string;setActive:(v:string)=>void;selectedPerson:string;setSelectedPerson:(v:string)=>void;locations:boolean;setLocations:(v:boolean)=>void;alerts:boolean;setAlerts:(v:boolean)=>void;compact:boolean;setCompact:(v:boolean)=>void};
function Content(p:Props){
  if(p.active==='Control center')return <ControlCenter/>;
  if(p.active==='People & groups')return <PeoplePage selected={p.selectedPerson} setSelected={p.setSelectedPerson}/>;
  if(p.active==='Trail devices')return <DevicesPage/>;
  if(p.active==='Communications')return <CommunicationsPage/>;
  if(p.active==='Locations')return <LocationsPage onOpenPerson={(name)=>{p.setSelectedPerson(name);p.setActive('People & groups')}}/>;
  if(p.active==='Safety & alerts')return <SafetyPage/>;
  if(p.active==='Server foundation')return <FoundationPage/>;
  if(p.active==='Offline readiness')return <OfflinePage/>;
  if(p.active==='Updates')return <UpdatesPage/>;
  if(p.active==='Backups')return <BackupsPage/>;
  if(p.active==='Server settings')return <SettingsPage compact={p.compact} setCompact={p.setCompact}/>;
  return <Page eyebrow="PROTOTYPE WORKSHOP" title="Questions to settle before development begins." desc="Keeping unresolved choices visible now should prevent expensive assumptions later."><div className="cards"><Idea tag="EXPLORE" title="Group check-in" text="One tap lets everyone know a member is safe."/><Idea tag="EXPLORE" title="Last known position" text="Keep a useful position when a device disconnects."/><Idea tag="DISCUSS" title="Private group codes" text="Join simply without an outside account."/></div><div className="panel questions"><h3>What we should decide next</h3><ol><li>Who operates the server, and what can members change?</li><li>How does a phone find it with no internet?</li><li>How much location and message history stays local?</li><li>What is the simplest safe onboarding and recovery process?</li><li>Which functions belong in the app versus this interface?</li></ol></div></Page>;
}

function FoundationPage(){return <div className="operational-page maintenance-page">
  <div className="page-tools"><div><strong>SERVER FOUNDATION — OPTION V0</strong><span>Host and service prototypes in progress · demonstration only</span></div><a href="https://github.com/Limited-Underground/Trail-Server" target="_blank" rel="noreferrer">Public repository</a></div>
  <div className="maintenance-grid">
    <section className="panel version-card"><span>TRAIL NETWORK INTERFACE</span><strong>Dedicated LoRa device</strong><small>A Trail-compatible server gateway participates in the radio network and connects to the Linux host through USB.</small></section>
    <section className="panel version-card"><span>SERVER APPLICATION</span><strong>ASP.NET Core</strong><small>One modular service owns the USB bridge, persistent radio queues, Trail processing, administration API, and web interface.</small></section>
    <section className="panel version-card"><span>DATA & LOCATION</span><strong>PostgreSQL + PostGIS</strong><small>Established relational and geographic storage for radio-received records, locations, tracks, queues, and audit history.</small></section>
    <section className="panel version-card"><span>WEB & LARGE FILES</span><strong>Caddy + MapLibre + PMTiles</strong><small>LAN administration by IP for the first functional release, plus bounded delivery of files too large for the LoRa network.</small></section>
  </div>
  <section className="panel maintenance-note"><div><strong>LINUX APPLIANCE</strong><span>Minimal Linux host, lightweight local browser interface, and LAN access to the same dashboard. Trusted HTTPS is deferred unless it becomes simple enough not to delay functionality.</span></div></section>
</div>}

function ControlCenter(){return <div className="control-center">
  <div className="status-strip">
    <div><span>PEOPLE</span><strong>4 / 4</strong><small>accounted for</small></div>
    <div><span>TRAIL DEVICES</span><strong>4</strong><small>online now</small></div>
    <div><span>NETWORK</span><strong>Ready</strong><small>dedicated server LoRa gateway</small></div>
    <div className="attention"><span>SAFETY</span><strong>1 advisory</strong><small>tree down · west loop</small></div>
  </div>
  <div className="control-grid">
    <section className="panel live-map"><Head a="LIVE OPERATIONS" b="Group location"/><Map/></section>
    <section className="panel watchlist"><Head a="GROUP STATUS" b="People requiring attention"/>
      <div className="advisory"><b>!</b><span><strong>Tree down</strong><small>West Loop · reported 12 min ago</small></span><button>View</button></div>
      {people.map((x,i)=><div className="person" key={x.name}><div className="avatar">{x.name[0]}</div><span><strong>{x.name}</strong><small>{i===1?'Moving · Jeep · 1,204 ft':x.place}</small></span><em>{i===2?'18 min ago':'● '+x.state}</em></div>)}
    </section>
    <section className="panel radio-feed"><Head a="RECENT COMMUNICATION" b="Latest messages"/><Message who="Alex · 2 min ago" text="Reached the north trailhead. Everything is clear here." note="Acknowledged by 3 of 3 recipients"/></section>
    <section className="panel next-check"><Head a="NEXT CHECK-IN" b="Jordan · Pine Overlook"/><strong>24 min</strong><span>Scheduled group check-in</span></section>
  </div>
</div>}

function OperationsDisplay({onExit}:{onExit:()=>void}){return <main className="wallboard">
  <header><div><p>LIMITED UNDERGROUND / TRAIL</p><h1>Pine Ridge Park</h1></div><div><span className="wall-online"><i/> DEMONSTRATION · SIMULATED NETWORK</span><button onClick={onExit}>Return to control center</button></div></header>
  <div className="wall-summary"><div><b>24 / 24</b><span>PEOPLE ACCOUNTED FOR</span></div><div><b>21</b><span>MOVING</span></div><div><b>3</b><span>STOPPED</span></div><div className="warn"><b>1</b><span>ACTIVE ADVISORY</span></div></div>
  <div className="wall-grid">
    <section className="wall-map"><Map/></section>
    <aside className="wall-attention"><h2>Needs attention</h2><article className="wall-alert"><b>TRAIL OBSTRUCTION</b><strong>Tree down · West Loop</strong><span>Reported by Dave · 12 min ago</span></article><h2>Group status</h2>{people.map((x,i)=><div className="wall-person" key={x.name}><b>{x.name[0]}</b><span><strong>{x.name}</strong><small>{i===1?'Jeep · moving · 1,204 ft':x.place}</small></span><em>{i===2?'18m':'NOW'}</em></div>)}</aside>
  </div>
  <div className="wall-footer"><span><b>LAST MESSAGE</b> Alex: Reached the north trailhead. Everything is clear.</span><strong>PERMANENT SITE · MODE: OFF-ROAD</strong></div>
</main>}

function PeoplePage({selected,setSelected}:{selected:string;setSelected:(v:string)=>void}){const current=people.find(x=>x.name===selected)||people[0];return <div className="operational-page people-page">
  <div className="page-tools"><div><strong>OFF-ROAD GROUP</strong><span>4 members · everyone accounted for</span></div><div><button>Manage teams</button><button className="primary">Add person</button></div></div>
  <div className="people-grid"><section className="panel member-list"><div className="list-head"><b>MEMBERS</b><span>STATUS</span></div>{people.map((x,i)=><button className={selected===x.name?'selected':''} key={x.name} onClick={()=>setSelected(x.name)}><span className="avatar">{x.name[0]}</span><span><strong>{x.name}</strong><small>{i===1?'Jeep · vehicle display':i===2?'Rugged touchscreen':'Phone + Trail device'}</small></span><em>{i===2?'18 min':'● Online'}</em></button>)}</section>
  <section className="panel member-detail"><div className="profile-title"><span className="avatar large">{current.name[0]}</span><div><h2>{current.name}</h2><p>{current.place} · position updated 2 min ago</p></div><button>Message</button></div><div className="profile-stats"><div><span>STATUS</span><strong>{current.state}</strong></div><div><span>ROLE</span><strong>{current.name==='Morgan'?'Coordinator':'Member'}</strong></div><div><span>CHECK-IN</span><strong>{current.name==='Casey'?'18 min ago':'Current'}</strong></div><div><span>DEVICE</span><strong>Trail {current.name==='Alex'?'One':current.name==='Jordan'?'Two':current.name==='Casey'?'Three':'Base'}</strong></div></div><div className="profile-section"><h3>Current field information</h3><Line a="Last known location" b={current.place}/><Line a="Battery" b={current.name==='Jordan'?'72%':'86%'}/><Line a="GPS" b="12 satellites"/><Line a="Interface" b={current.name==='Jordan'?'Vehicle display':current.name==='Casey'?'Rugged touchscreen':'Phone'}/></div><div className="profile-actions"><button>Locate on map</button><button>Request check-in</button><button>View recent activity</button></div></section></div>
</div>}

function DeviceGlyph({type}:{type:string}){return <span className="device-glyph"><b>⌁</b><i>{type==='Phone'?'▯':type==='Rugged touchscreen'?'▣':type==='Vehicle display'?'◴':'·'}</i></span>}
function DevicesPage(){const rows=[['Trail One','Alex','Phone','86%','12','Online'],['Trail Two','Jordan','Vehicle display','72%','9','Online'],['Trail Three','Casey','Rugged touchscreen','94%','11','Online'],['Server Gateway','Server','Dedicated USB radio','100%','14','Online']];return <div className="operational-page devices-page"><div className="page-tools"><div><strong>TRAIL DEVICES</strong><span>4 online · 0 requiring attention</span></div><div><button>Identify device</button><button className="primary">Assign device</button></div></div><section className="panel device-table"><div className="device-row device-labels"><span>INTERFACE</span><span>DEVICE</span><span>ASSIGNED</span><span>BATTERY</span><span>GPS</span><span>LAST CONTACT</span><span>STATUS</span></div>{rows.map((x,i)=><button className="device-row" key={x[0]}><DeviceGlyph type={x[2]}/><strong>{x[0]}<small>{x[2]}</small></strong><span>{x[1]}</span><span className={i===1?'battery-mid':''}>{x[3]}</span><span>{x[4]} sat</span><span>{i===2?'1 min ago':'Just now'}</span><span className="device-online">● {x[5]}</span></button>)}</section><div className="device-note"><b>INTERFACE ICONS</b><span>Trail endpoints may use a phone, integrated touchscreen, or another local interface. The server uses its own dedicated USB-connected Trail LoRa device.</span></div></div>}

function CommunicationsPage(){const [conversation,setConversation]=useState('Entire Group');const [draft,setDraft]=useState('');const presets=['Check in','Hold position','Return to base','Need assistance?','All clear'];return <div className="operational-page communications-page"><div className="comms-shell panel"><aside className="conversations"><header><strong>CONVERSATIONS</strong><button>＋</button></header>{['Entire Group','Trail Leaders','Alex','Jordan','Casey','Morgan'].map((x,i)=><button key={x} className={conversation===x?'selected':''} onClick={()=>setConversation(x)}><span className="avatar">{x[0]}</span><span><strong>{x}</strong><small>{i===0?'4 members':i===1?'2 members':'● Online'}</small></span>{i===3&&<em>2</em>}</button>)}</aside><section className="chat"><header><div><strong>{conversation}</strong><span>{conversation==='Entire Group'?'4 members · local Trail network':'Direct local conversation'}</span></div><button>Details</button></header><div className="chat-history"><Message who="Alex · 9:42 AM" text="Reached the north trailhead. Everything is clear here." note="Acknowledged by 3 of 3 recipients"/><Message reply who="Base Camp · 9:44 AM" text="Copy. Check in again at Pine Overlook." note="Device acknowledged"/><Message who="Jordan · 9:51 AM" text="Tree down on West Loop. Marking the location now." note="Acknowledged by 3 of 3 recipients"/></div><div className="presets">{presets.map(x=><button key={x} onClick={()=>setDraft(x)}>{x}</button>)}</div><form className="composer" onSubmit={(e)=>e.preventDefault()}><textarea aria-label="Message" value={draft} onChange={e=>setDraft(e.target.value)} placeholder={'Message '+conversation}/><span>{draft.length}/160</span><button className="primary">Send</button></form></section></div></div>}

function LocationsPage({onOpenPerson}:{onOpenPerson:(name:string)=>void}){const [selected,setSelected]=useState('Jordan');return <div className="operational-page locations-page"><div className="map-toolbar"><div><strong>LIVE LOCATIONS</strong><span>4 current · 0 stale · 1 active issue</span></div><div><button>Find person</button><button>Fit group</button><button>Trails</button><button>Layers</button></div></div><section className="location-map"><span className="trail-name ridge">NORTH RIDGE</span><span className="trail-name creek">PINE CREEK</span><div className="issue-marker"><b>!</b><span>Tree down</span></div>{people.map((x,i)=><button className={'location-pin lp'+i+(selected===x.name?' selected':'')} key={x.name} onClick={()=>setSelected(x.name)}><b>{x.name[0]}</b><span>{x.name}</span></button>)}<div className="map-legend"><span><i className="fresh"/>Current</span><span><i className="stale"/>Stale</span><span><i className="issue"/>Trail issue</span></div>{selected&&<aside className="map-popup"><header><span className="avatar">{selected[0]}</span><div><strong>{selected}</strong><small>Position updated 2 min ago</small></div></header><Line a="Status" b={selected==='Jordan'?'Moving · Jeep':'Connected'}/><Line a="Elevation" b={selected==='Jordan'?'1,204 ft':'1,118 ft'}/><Line a="Battery" b={selected==='Jordan'?'72%':'86%'}/><Line a="GPS" b="12 satellites"/><div><button>Message {selected}</button><button className="primary" onClick={()=>onOpenPerson(selected)}>View complete profile</button></div></aside>}</section></div>}

function SafetyPage(){return <div className="operational-page safety-page"><div className="safety-summary"><div className="safe"><span>ACCOUNTABILITY</span><strong>4 / 4</strong><small>all members accounted for</small></div><div><span>IMMEDIATE</span><strong>0</strong><small>unacknowledged emergencies</small></div><div className="warning"><span>TEMPORARY</span><strong>1</strong><small>active condition</small></div><div><span>STANDING</span><strong>2</strong><small>site notices</small></div></div><div className="safety-grid"><section className="panel alert-queue"><div className="section-title"><div><strong>ACTIVE SAFETY & ALERTS</strong><span>Highest priority first</span></div><button>Create alert</button></div><article className="alert-row temporary"><span className="alert-type">TEMPORARY</span><div><strong>Tree down · West Loop</strong><p>Reported by Jordan at 9:51 AM · confirmed by Alex · affects marked trail segment</p><small>Last confirmed 8 minutes ago</small></div><em>ACTIVE</em><button>Open</button></article><article className="alert-row standing"><span className="alert-type">STANDING</span><div><strong>South Bridge closed</strong><p>Unsafe crossing · closure applies to every active operation</p><small>Authorized by Pine Ridge Park staff</small></div><em>IN EFFECT</em><button>Open</button></article><article className="alert-row standing"><span className="alert-type">STANDING</span><div><strong>Fire restriction</strong><p>No open flames beyond base camp</p><small>Site notice · reviewed today</small></div><em>IN EFFECT</em><button>Open</button></article></section><aside className="panel accountability"><div className="section-title"><div><strong>CHECK-INS</strong><span>Next scheduled responses</span></div></div><div className="checkin"><span>24 min</span><div><strong>Jordan</strong><small>Pine Overlook</small></div><button>Message</button></div><div className="checkin"><span>38 min</span><div><strong>Entire Group</strong><small>Scheduled group check-in</small></div><button>Details</button></div><div className="safety-rules"><strong>ALERT HANDLING</strong><p>Acknowledging confirms the alert was seen. It does not resolve the condition.</p><button>View resolved history</button></div></aside></div></div>}

function OfflinePage(){const checks=[['Linux server','Simulated'],['Dedicated server radio','Demo connection'],['Recent devices','4 synthetic'],['Offline map area','Demo package'],['Radio queues','Demonstration state'],['Large-file service','Simulated LAN service']];return <div className="operational-page maintenance-page"><div className="readiness-hero"><div><span>DEMONSTRATION READINESS</span><strong>SIMULATED</strong><p>Illustrative status only; no live radio or operational service is connected.</p></div><b>◇</b></div><div className="readiness-grid">{checks.map(x=><div key={x[0]}><b>◇</b><span><strong>{x[0]}</strong><small>{x[1]}</small></span></div>)}</div><section className="panel maintenance-note"><div><strong>DEMO SNAPSHOT</strong><span>Synthetic example</span></div><button>Run demonstration</button></section></div>}
function UpdatesPage(){return <div className="operational-page maintenance-page"><div className="page-tools"><div><strong>SERVER & DEVICE UPDATES</strong><span>Review, schedule, and recover deliberately</span></div><button>Check for updates</button></div><div className="maintenance-grid"><section className="panel version-card"><span>CURRENT SERVER VERSION</span><strong>Prototype build 1</strong><small>Installed locally · no update pending</small><div className="ok-line">✓ System is current</div></section><section className="panel version-card"><span>DEVICE FIRMWARE</span><strong>4 current</strong><small>All connected Trail devices match the approved release</small><div className="ok-line">✓ No mismatched devices</div></section><section className="panel update-policy"><strong>INSTALLATION POLICY</strong><Line a="Download" b="When available"/><Line a="Install" b="Operator approval required"/><Line a="Field operation" b="Never interrupt automatically"/></section><section className="panel update-policy"><strong>RECOVERY</strong><Line a="Last known-good server" b="Available"/><Line a="Last known-good firmware" b="Available"/><button>Review recovery packages</button></section></div></div>}
function BackupsPage(){return <div className="operational-page maintenance-page"><div className="page-tools"><div><strong>LOCAL BACKUPS</strong><span>Demonstration of configuration and operation-record workflows</span></div><div><button>Restore demo</button><button className="primary">Create demo backup</button></div></div><div className="backup-grid"><section className="panel backup-health"><span>BACKUP STATUS</span><strong>Demonstration</strong><small>Synthetic backup history; no restore evidence is represented</small><div><Line a="Automatic backup" b="Example schedule"/><Line a="Portable copy" b="Example only"/><Line a="Restore verification" b="Not performed"/></div></section><section className="panel backup-list"><div className="section-title"><div><strong>EXAMPLE BACKUPS</strong><span>Synthetic records</span></div></div>{[['Today · 2:00 AM','Automatic example','Example'],['Yesterday · 2:00 AM','Automatic example','Example'],['Aug 24 · 4:18 PM','Portable export example','Example']].map(x=><div className="backup-row" key={x[0]}><span><strong>{x[0]}</strong><small>{x[1]}</small></span><b>◇ {x[2]}</b><button>Details</button></div>)}</section></div></div>}
function SettingsPage({compact,setCompact}:{compact:boolean;setCompact:(v:boolean)=>void}){return <div className="settings-page"><div className="page-tools"><div><strong>SERVER SETTINGS</strong><span>Changes here affect this Trail Server installation</span></div><button className="primary">Save changes</button></div><section className="panel settings-group"><h2>Deployment</h2><Setting title="Deployment type" text="Permanent Site · retains long-lived site information"><button>Change</button></Setting><Setting title="Site name" text="Pine Ridge Park"><button>Edit</button></Setting><Setting title="Operating mode" text="Off-road"><button>Change</button></Setting></section><section className="panel settings-group"><h2>Linux server</h2><Setting title="Server name" text="Trail Server · Base Camp"><button>Edit</button></Setting><Setting title="LAN address" text="Assigned IP with DHCP reservation"><button>Review</button></Setting><Setting title="Compact layout" text="Reduce spacing for smaller screens"><Toggle value={compact} set={setCompact}/></Setting><Setting title="IP file service" text="For files too large for the LoRa network"><strong>Optional</strong></Setting></section><section className="panel settings-group"><h2>Privacy & retention</h2><Setting title="Member location sharing" text="Enabled for the active operation"><button>Review</button></Setting><Setting title="Resolved trail issues" text="Retain in local history"><button>Review</button></Setting></section></div>}

function Page({eyebrow,title,desc,children}:{eyebrow:string;title:string;desc:string;children:React.ReactNode}){return <><div className="intro"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{desc}</p></div>{children}</>}
function Head({a,b}:{a:string;b:string}){return <div className="head"><p className="eyebrow">{a}</p><h3>{b}</h3></div>}
function Line({a,b}:{a:string;b:string}){return <div className="line"><span>{a}</span><strong>{b}</strong></div>}
function Idea({tag,title,text}:{tag:string;title:string;text:string}){return <article className="card idea"><span>{tag}</span><h3>{title}</h3><p>{text}</p><button>Explore this idea →</button></article>}
function Setting({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <div className="setting"><div><strong>{title}</strong><span>{text}</span></div>{children}</div>}
function Toggle({value,set}:{value:boolean;set:(v:boolean)=>void}){return <button aria-label={value?'Enabled':'Disabled'} aria-pressed={value} className={'toggle '+(value?'on':'')} onClick={()=>set(!value)}><i/></button>}
function Message({who,text,note,reply=false}:{who:string;text:string;note:string;reply?:boolean}){return <div className={'message '+(reply?'reply':'')}><small>{who}</small><p>{text}</p><em>{note}</em></div>}
function Map({disabled=false}:{disabled?:boolean}){return <div className={'map '+(disabled?'disabled':'')}><span>NORTH RIDGE</span><span>PINE CREEK</span>{!disabled&&people.map((x,i)=><div className={'pin p'+i} key={x.name}><b>{x.name[0]}</b><small>{x.name}<em>{x.place}</em></small></div>)}{disabled&&<strong>Location sharing is off</strong>}<footer>Mock local positions · under 2 min old</footer></div>}
function icon(item:string){const x:Record<string,string>={'Control center':'⌂','Operations display':'▤','People & groups':'◎','Trail devices':'⌁',Communications:'↔',Locations:'⌖','Safety & alerts':'!','Server foundation':'▦','Offline readiness':'✓',Updates:'↻',Backups:'▣','Server settings':'⚙'};return x[item]}
